language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - ruby-head
  - jruby-19mode
  - rbx-19mode
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq poppler-utils jabref
matrix:
  allow_failures:
    - rvm: ruby-head
